# Generated by Django 4.0.4 on 2022-05-23 08:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='createdate',
            field=models.DateTimeField(blank=True, verbose_name=datetime.datetime(2022, 5, 23, 17, 46, 0, 21117)),
        ),
        migrations.AlterField(
            model_name='member',
            name='gender',
            field=models.CharField(default='남자', max_length=10),
        ),
        migrations.AlterField(
            model_name='member',
            name='updatedate',
            field=models.DateTimeField(blank=True, verbose_name=datetime.datetime(2022, 5, 23, 17, 46, 0, 21134)),
        ),
    ]
