# Generated by Django 4.0.4 on 2022-05-16 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='s_date',
            field=models.DateField(auto_now=True),
        ),
    ]
