# Generated by Django 4.0.4 on 2022-05-19 09:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('s_no', models.AutoField(primary_key=True, serialize=False)),
                ('s_id', models.CharField(max_length=30)),
                ('s_pw', models.CharField(max_length=100)),
                ('s_name', models.CharField(max_length=100)),
                ('s_tel', models.CharField(max_length=13)),
                ('s_zipcode', models.CharField(max_length=5)),
                ('s_ads1', models.CharField(max_length=1000)),
                ('s_ads2', models.CharField(max_length=1000)),
                ('s_date', models.DateTimeField(blank=True, default=datetime.datetime(2022, 5, 19, 18, 4, 31, 407528))),
            ],
        ),
    ]
