# Generated by Django 4.0.4 on 2022-05-24 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('pNo', models.AutoField(primary_key=True, serialize=False)),
                ('pName', models.CharField(max_length=100)),
                ('pServing', models.CharField(max_length=100)),
                ('pUnitPrice', models.IntegerField(verbose_name=10)),
                ('pDescription', models.TextField()),
                ('pCategory', models.CharField(max_length=20)),
                ('pManufacturer', models.CharField(max_length=20)),
                ('pUnit', models.IntegerField(verbose_name=20)),
                ('pFileName', models.ImageField(upload_to='', verbose_name=100)),
            ],
        ),
    ]
