# Generated by Django 4.0.4 on 2022-05-24 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='pFileName',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='product',
            name='pUnit',
            field=models.IntegerField(default=20),
        ),
        migrations.AlterField(
            model_name='product',
            name='pUnitPrice',
            field=models.IntegerField(default=0, max_length=10),
        ),
    ]
