# Generated by Django 4.0.4 on 2022-05-23 01:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('mId', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('mPw', models.CharField(max_length=300)),
                ('mName', models.CharField(max_length=100)),
                ('mNickname', models.CharField(max_length=100)),
                ('mTel', models.CharField(blank=True, max_length=13)),
                ('mzipcode', models.CharField(blank=True, max_length=6)),
                ('maddress1', models.CharField(blank=True, max_length=300)),
                ('maddress2', models.CharField(blank=True, max_length=300)),
                ('mgender', models.CharField(default='남자', max_length=10)),
                ('mhobby', models.CharField(blank=True, max_length=100)),
                ('mCreatedate', models.DateTimeField(blank=True, default=datetime.datetime(2022, 5, 23, 10, 21, 39, 366601))),
                ('mUpdatedate', models.DateTimeField(blank=True, default=datetime.datetime(2022, 5, 23, 10, 21, 39, 366601))),
            ],
        ),
    ]
