# Generated by Django 4.0.4 on 2022-05-24 02:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0008_alter_member_mcreatedate_alter_member_mupdatedate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='mCreatedate',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 5, 24, 11, 20, 1, 826769)),
        ),
        migrations.AlterField(
            model_name='member',
            name='mUpdatedate',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 5, 24, 11, 20, 1, 826769)),
        ),
    ]
