# Generated by Django 4.0.4 on 2022-05-23 01:56

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('member', '0003_alter_member_mcreatedate_alter_member_mupdatedate'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fboard',
            fields=[
                ('fNo', models.AutoField(primary_key=True, serialize=False)),
                ('fTitle', models.CharField(max_length=1000)),
                ('fContent', models.TextField()),
                ('fGroup', models.IntegerField(default=0)),
                ('fStep', models.IntegerField(default=0)),
                ('fIndent', models.IntegerField(default=0)),
                ('fHit', models.IntegerField(default=1)),
                ('fCreatedate', models.DateTimeField(blank=True, default=datetime.datetime(2022, 5, 23, 10, 56, 16, 953586))),
                ('fUpdatedate', models.DateTimeField(blank=True, default=datetime.datetime(2022, 5, 23, 10, 56, 16, 953586))),
                ('fFile', models.ImageField(blank=True, upload_to='')),
                ('fmember', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='member.member')),
            ],
        ),
    ]
