# Generated by Django 4.0.4 on 2022-05-23 02:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fboard',
            name='fCreatedate',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 5, 23, 11, 2, 55, 68389)),
        ),
        migrations.AlterField(
            model_name='fboard',
            name='fUpdatedate',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 5, 23, 11, 2, 55, 68389)),
        ),
    ]
