# Generated by Django 4.0.4 on 2022-05-23 04:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fboard', '0005_alter_fboard_fcreatedate_alter_fboard_fupdatedate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fboard',
            name='fCreatedate',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 5, 23, 13, 45, 21, 766925)),
        ),
        migrations.AlterField(
            model_name='fboard',
            name='fUpdatedate',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 5, 23, 13, 45, 21, 766925)),
        ),
    ]
