# Generated by Django 4.0.4 on 2022-05-24 02:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fboard', '0007_alter_fboard_fcreatedate_alter_fboard_fupdatedate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fboard',
            name='fCreatedate',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 5, 24, 11, 35, 22, 12353)),
        ),
        migrations.AlterField(
            model_name='fboard',
            name='fUpdatedate',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 5, 24, 11, 35, 22, 12353)),
        ),
    ]
