# Generated by Django 4.0.4 on 2022-06-08 05:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fboard', '0002_alter_fboard_f_createdate_alter_fboard_f_updatedate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fboard',
            name='f_createdate',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 6, 8, 14, 55, 56, 400179)),
        ),
        migrations.AlterField(
            model_name='fboard',
            name='f_updatedate',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 6, 8, 14, 55, 56, 400189)),
        ),
    ]
