# Generated by Django 4.0.4 on 2022-05-18 03:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='s_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 5, 18, 12, 6, 53, 601976)),
        ),
    ]
