# Generated by Django 4.0.4 on 2022-05-20 08:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('Z_no', models.AutoField(primary_key=True, serialize=False)),
                ('id', models.CharField(max_length=100)),
                ('Z_title', models.CharField(max_length=1000)),
                ('Z_content', models.TextField()),
                ('Z_group', models.IntegerField(default=0)),
                ('Z_step', models.IntegerField(default=0)),
                ('Z_indent', models.IntegerField(default=0)),
                ('Z_hit', models.IntegerField(default=1)),
                ('Z_createdate', models.DateTimeField(blank=True, default=datetime.datetime(2022, 5, 20, 8, 4, 48, 277607))),
                ('Z_updatedate', models.DateTimeField(blank=True, default=datetime.datetime(2022, 5, 20, 8, 4, 48, 277624))),
                ('Z_file', models.ImageField(blank=True, upload_to='')),
            ],
        ),
    ]
