# Generated by Django 4.0.4 on 2022-05-20 08:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='Z_createdate',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 5, 20, 8, 6, 6, 949212)),
        ),
        migrations.AlterField(
            model_name='board',
            name='Z_updatedate',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 5, 20, 8, 6, 6, 949233)),
        ),
    ]
