# Generated by Django 4.0.4 on 2022-05-20 08:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0002_alter_board_z_createdate_alter_board_z_updatedate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='Z_createdate',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 5, 20, 17, 10, 7, 945327)),
        ),
        migrations.AlterField(
            model_name='board',
            name='Z_updatedate',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 5, 20, 17, 10, 7, 945345)),
        ),
    ]
